### ISSUE TITLE
builder makes ONLY white backpaks and no sorting in it. (1.10.2)

### ISSUE THREAD

**Issue by ircmaan** [tobystrong/CompactStorage#43]
Some time ago it was in 1.7.10.
Now I see in again in 1.10.2
Can you help us?
Thanx

**Comment by MokahTGS** [comment]
Chests will also loose their color but not nbt tag when you break and replace them.

**Comment by tobystrong** [comment]
Fixed the color issues, not the sorting. I assume you mean sorting with InventoryTweaks?

**Comment by MokahTGS** [comment]
Yes or any sorting mod

**Comment by tobystrong** [comment]
Sorting won't be fixed with InvTweaks until they update to 1.11.2, if you can provide other mods that aren't working I can look into them.
