### ISSUE TITLE
java.lang.NumberFormatException: For input string: ")"

### ISSUE THREAD

**Issue by zackeezy** [tobystrong/CompactStorage#44]
<h3>Description</h3>

I deleted the "FFFFFF" for the color text and left it blank for a second and when I tried typing into it, it threw a pretty bad exception.  I think I typed a ) instead of 0.  The text box doesn't have a robust way of handling invalid input.

<h3>Context</h3>

Singleplayer using the curse launcher running a custom modpack.
http://pastebin.com/Xb254ti5 

**CompactStorage version:** compactstorage-2.1-1.9.4
**Minecraft version:** 1.10.2
**Forge Version:** forge-12.18.3.2185

**Comment by tobystrong** [comment]
This behaviour is being changed in the next update.
