### ISSUE TITLE
1.10.2 Crash with LAN player making backpacks

### ISSUE THREAD

**Issue by MokahTGS** [tobystrong/CompactStorage#45]
Getting a crash when a player makes a backpack in a LAN environment:

http://pastebin.com/rRtySiZb

**Comment by tobystrong** [comment]
Should be fixed in 2.1.1 for 1.11.2, if not please let me know :)

**Comment by MokahTGS** [comment]
Not sure if you saw that this was for the 1.10.2 version.  We do not use 1.11.2.
