### ISSUE TITLE
[1.10.2] Refined Storage External Storage Bug

### ISSUE THREAD

**Issue by MokahTGS** [tobystrong/CompactStorage#51]
The refined Storage Mod has external storage readers that are unable to attach to the Compact Storage chests.  They simply disappear when you try to attach them.  This makes CS incompatible with any refined storage computer system...

They used to work in 1.10.2 so something changed with the new upgrade.  I bet this is the same issue that affects signs not able to attach to them.  Please fix ASAP.

**Comment by tobystrong** [comment]
This was intentionally removed as it was hard to maintain - will look into fixing.

**Comment by MokahTGS** [comment]
If you fix this, please do it for the 1.12.2 versions as well as I and many others have moved on from 1.10
