### ISSUE TITLE
[1.11.2] Problem with a Tweaks mod

### ISSUE THREAD

**Issue by Malkierian** [tobystrong/CompactStorage#52]
I say that because I don't know if it's Inventory Tweaks or Mouse Tweaks, but when trying to deposit a bunch of stuff in a CompactChest, typically I would use Ctrl+Shift+Left click to move all stacks of the particular type at once, which works in almost everything else, but only moves the one stack when the CS gui is open.

**Comment by tobystrong** [comment]
Fixed in 2.3
