### ISSUE TITLE
GUI too big for screen

### ISSUE THREAD

**Issue by panoskj** [tobystrong/CompactStorage#56]
When using "GUI Scale: auto" the GUI may be too big to fit the screen. Here is a screenshot https://imgur.com/a/Ci0Je. I believe the GUI could be scaled down on this case.

**Comment by panoskj** [comment]
Here is a fix: [GuiChest.txt](https://github.com/tobystrong/CompactStorage/files/1822646/GuiChest.txt)

I added GuiChest.scaling and GuiChest.setWorldAndResolution as well as modified GuiChest.drawScreen.

**Comment by tobystrong** [comment]
Wow I've never noticed there's a fix for this, I'll take a look!

**Comment by panoskj** [comment]
There's also a better way: https://github.com/panoskj/CompactStorage/tree/gui-scales-down

But it requires FML to fix a vanilla bug. I made an issue https://github.com/MinecraftForge/MinecraftForge/issues/4814 but they don't seem to like my idea.

**Comment by henry860910** [comment]
how can i use this txt for fix this mod
