### ISSUE TITLE
Chest & Backpack problems

### ISSUE THREAD

**Issue by mihartsy** [tobystrong/CompactStorage#58]
Few problems

BACKPACK:
1. The sound of the backpack sounds like a chest
2. When you open the backpack it says chest instead of backpack

CHEST:
1. When you color the chest, the color doesn't show in the inventory, it stays white but when placed it changes to the color it's supposed to be.
2. The hit box of the chest is a full block, unlike the regular minecraft chest.

**Comment by tobystrong** [comment]
I'll take a look at these, I'll try find a sound that'd fit the backpack more!

**Comment by tobystrong** [comment]
1: I've replaced the sounds with more cloth sounding sounds, I think these sound a lot better!
2: I've fixed this, it was always meant to say Backpack but checking for a custom anvil name seems to have broken this!

1: This has been fixed! The logic was always in the code but the model was missing tint indexes, whoops!
2: Fixed!
